apiVersion: batch/v1
kind: Job
metadata:
  name: access-data-spark
spec:
  template:
    spec:
      containers:
        - name: python-container-2
          image: access-data-spark:v2
          imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 4
