apiVersion: batch/v1
kind: Job
metadata:
  name: access-data-spark
spec:
  template:
    spec:
      containers:
        - name: python-container
          image: maver02/access-data-spark:latest
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 4
